### ISSUE TITLE
Storing auth token and secret in request.session right now.  Very bad.

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/sentiment_analysis#18]
A temporary fix so devin can get the basic D3 up and running.
Was getting the error 
`ProgrammingError at /twit/callback
relation "auth_user" does not exist
LINE 1: SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."userna...
                               ^
Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/twit/callback?oauth_token=zVmU3rIfL9yluKT4nrvJEVtuRFuR12kV&oauth_verifier=0DkZDk1Sh75FdqMDBPu9G4wbyET1Lvbz
Django Version: 	1.7.2
Exception Type: 	ProgrammingError
Exception Value: 	
relation "auth_user" does not exist
LINE 1: SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."userna...
                               ^
Exception Location: 	/home/computeruser/byteacademy/sentiment_analysis/venv/lib/python3.4/site-packages/django/db/backends/utils.py in execute, line 65
Python Executable: 	/home/computeruser/byteacademy/sentiment_analysis/venv/bin/python3
Python Version: 	3.4.0
Python Path: 	
['/home/computeruser/byteacademy/sentiment_analysis/project',
 '/home/computeruser/byteacademy/sentiment_analysis/venv/lib/python3.4',
 '/home/computeruser/byteacademy/sentiment_analysis/venv/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/computeruser/byteacademy/sentiment_analysis/venv/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/computeruser/byteacademy/sentiment_analysis/venv/lib/python3.4/site-packages']
Server time: 	Sat, 10 Jan 2015 01:38:00 +0000`
When trying to use the app with as was imported.  So, I commented out the User parts in the Callback and Results classes in twit.views.  This needs to be addressed soon.

**Comment by adolfo0620** [comment]
can't we use redis for this?

**Comment by derek-dchu** [comment]
To me, I found that it cant use oauth_token. It needs to use access_token for the stream api.

**Comment by adolfo0620** [comment]
so we can't store the oauth_token and access_token in redis?

**Comment by adolfo0620** [comment]
the oauth_token and the access_token doesnt change, until a new one is aked and the old ones "expire", both are being save now, try to install redis last but failed

**Comment by derek-dchu** [comment]
We will save final token to db as usual.
