### ISSUE TITLE
AUTH_USER_MODEL should be 'twit.models.User'

### ISSUE THREAD

**Issue by derek-dchu** [himleyb85/sentiment_analysis#19]
I seems twit.User doesn't get the User model correctly.

**Comment by wmantly** [comment]
Where going to use the django built in User model.

**Comment by derek-dchu** [comment]
Ok. Another way around is using one to one relation to add additional fields to User.

**Comment by wmantly** [comment]
Thanks Derek, ill make sure who ever writes that part of the code sees this.
