### ISSUE TITLE
API logic

### ISSUE THREAD

**Issue by wmantly** [himleyb85/sentiment_analysis#29]
At the moment, the API logic would have a large big O, this can and should be brought down.

**Comment by wmantly** [comment]
Just noticed #12, this is related.

**Comment by derek-dchu** [comment]
Two things we can do are, transforming dictionary from arrays to dictionary with weights, and caching repeated words in dictionary. These will reduce the run to O(n), which equals one iteration of text content.

**Comment by himleyb85** [comment]
both the positive and negative lists have more than 4 thousand words in them.  I'm not about to go through and add weight to all of them, but I changed the arrays to sets to take away the O(n) lookup time of the arrays.  @derek-dchu what do you mean by caching repeated words in text?

**Comment by wmantly** [comment]
What i think he means is to make a word list out of each block of text to be evaluated, and making sure its unique.

**Comment by himleyb85** [comment]
why should it be unique?  shouldn't the negative score go up twice if there are two negative words?

**Comment by wmantly** [comment]
Correct, but to keep the big O, each unique word should only be checked once.
