### ISSUE TITLE
Twitter API only allows 300 tweets to be retreived every 15 minutes

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/sentiment_analysis#4]
For large scale historical analysis, we must store all the tweets in our own database by running a script that queries every 15 minutes

**Comment by wmantly** [comment]
Clarification, its 300 API calls, not tweets per se.

**Comment by wmantly** [comment]
We can use better filtering and server-side caching to get the most out of every API call.

**Comment by derek-dchu** [comment]
Will be great to add a reference link, that we can have a clear understanding of limitations.

**Comment by adolfo0620** [comment]
Rate limits

The GET search/tweets is part of the Twitter REST API 1.1 and is rate limited similarly to other v1.1 methods. See REST API Rate Limiting in v1.1 for information on that model. At this time, users represented by access tokens can make 180 requests/queries per 15 minutes. Using application-only auth, an application can make 450 queries/requests per 15 minutes on its own behalf without a user context.

**Comment by adolfo0620** [comment]
https://dev.twitter.com/rest/public/search
